// Docs build: generates everything the Jekyll cheat sheet in docs/ consumes,
// derived from the font build's outputs. Strictly independent of scripts/build.mjs:
// it reads dist/lobe-icons.ttf + codepoints.json and errors if the font is unbuilt.
//
// Emits (all gitignored):
//   docs/assets/lobe-icons.ttf   copy of the built font
//   docs/assets/lobe-icons.css   @font-face + .li base + .li-<slug>::before classes
//   docs/_data/icons.json        [{ slug, title, codepoint, hex }] for the grid
//
// Titles come from @lobehub/icons es/<Name>/style.js (TITLE), joined to our slug
// via lowercased folder name — the same slug rule scripts/build.mjs uses.

import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ICONS_PKG = join(ROOT, "node_modules/@lobehub/icons/es");
const DIST_TTF = join(ROOT, "dist/lobe-icons.ttf");
const CODEPOINTS_PATH = join(ROOT, "codepoints.json");
const ASSETS_DIR = join(ROOT, "docs/assets");
const DATA_DIR = join(ROOT, "docs/_data");

const FONT_FAMILY = "Lobe Icons";
const CLASS_PREFIX = "li";

async function main() {
  const codepoints = readCodepoints();
  const titles = await readTitles();

  const icons = Object.entries(codepoints)
    .map(([slug, codepoint]) => ({
      slug,
      title: titles.get(slug) ?? slug,
      codepoint,
      hex: codepoint.toString(16).toUpperCase(),
    }))
    .sort((left, right) => left.slug.localeCompare(right.slug));

  mkdirSync(ASSETS_DIR, { recursive: true });
  mkdirSync(DATA_DIR, { recursive: true });

  copyFileSync(DIST_TTF, join(ASSETS_DIR, "lobe-icons.ttf"));
  writeFileSync(join(ASSETS_DIR, "lobe-icons.css"), renderCss(icons));
  writeFileSync(
    join(DATA_DIR, "icons.json"),
    `${JSON.stringify(icons, null, 2)}\n`,
  );

  console.log(`generated site assets for ${icons.length} icons`);
  console.log("  docs/assets/lobe-icons.ttf");
  console.log("  docs/assets/lobe-icons.css");
  console.log("  docs/_data/icons.json");
}

function readCodepoints() {
  let raw;
  try {
    raw = readFileSync(CODEPOINTS_PATH, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error(
        "codepoints.json not found. Run `npm run build` first to build the font.",
      );
    }
    throw error;
  }
  return JSON.parse(raw);
}

// Map slug -> TITLE by importing each es/<Name>/style.js (plain ESM, no React).
async function readTitles() {
  let entries;
  try {
    entries = readdirSync(ICONS_PKG, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error("@lobehub/icons not installed. Run `npm install` first.");
    }
    throw error;
  }

  const titles = new Map();
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const stylePath = join(ICONS_PKG, entry.name, "style.js");
    try {
      const module = await import(pathToFileURL(stylePath).href);
      if (module.TITLE) titles.set(entry.name.toLowerCase(), module.TITLE);
    } catch (error) {
      if (error.code === "ERR_MODULE_NOT_FOUND") continue;
      throw error;
    }
  }
  return titles;
}

function renderCss(icons) {
  const header = `/* Generated by scripts/build-docs.mjs. Do not edit. */`;
  const fontFace = [
    `@font-face {`,
    `  font-family: "${FONT_FAMILY}";`,
    `  src: url("lobe-icons.ttf") format("truetype");`,
    `  font-display: block;`,
    `}`,
  ].join("\n");
  const base = [
    `.${CLASS_PREFIX} {`,
    `  font-family: "${FONT_FAMILY}";`,
    `  font-style: normal;`,
    `  font-weight: normal;`,
    `  font-variant: normal;`,
    `  line-height: 1;`,
    `  text-transform: none;`,
    `  display: inline-block;`,
    `  -webkit-font-smoothing: antialiased;`,
    `  -moz-osx-font-smoothing: grayscale;`,
    `}`,
  ].join("\n");
  const glyphs = icons
    .map(
      (icon) =>
        `.${CLASS_PREFIX}-${icon.slug}::before { content: "\\${icon.hex}"; }`,
    )
    .join("\n");

  return `${header}\n\n${fontFace}\n\n${base}\n\n${glyphs}\n`;
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
